---
platform: linux
image: docker:///cloudfoundry/cli-ci

inputs:
  - name: cf-cli
    path: gopath/src/github.com/cloudfoundry/cli

run:
  path: sh
  args:
  - -c
  - |
    set -e -x

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    cd $GOPATH/src/github.com/cloudfoundry/cli
    bin/test
