---
groups:
- name: cli
  jobs:
  - linux64-unit
  - linux32-unit
  - darwin64-unit
  - win64-unit
  - win32-unit
  - linux64-gats
  - linux64-cats
- name: bosh-lite
  jobs: [provision-linux, provision-windows]
- name: concourse
  jobs: [deploy-concourse]

resources:
- name: cf-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: concourse

- name: cli-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-ci.git
    branch: concourse
    private_key: {{ci-repo-private-key}}

- name: cf-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-lite.git
    branch: master

- name: cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: master

- name: bosh-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-lite.git
    branch: master

- name: gats
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/GATS
    branch: master

- name: concourse-deployment
  type: bosh-deployment
  source:
    target: {{concourse-bosh-target}}
    username: {{concourse-bosh-username}}
    password: {{concourse-bosh-password}}
    deployment: concourse
    ignore_ssl: true

- name: concourse
  type: github-release
  source:
    user: concourse
    repository: concourse

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

jobs:
- name: linux64-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.linux.yml

- name: linux32-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.linux32.yml

- name: darwin64-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.darwin.yml

- name: win32-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.windows32.yml

- name: win64-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.windows.yml

- name: linux64-cats
  serial_groups: [bosh-lite-linux]
  plan:
  - aggregate:
    - get: cf-cli
      passed: [linux64-unit]
    - get: cli-ci
      trigger: false
    - get: cf-release
      trigger: false
      passed: [provision-linux]
      params:
        submodules:
          - src/acceptance-tests
  - task: cats
    file: cf-cli/ci/cats.linux.yml
    config:
      params:
        BOSH_LITE_IP: {{bosh-lite-ip-linux}}

- name: linux64-gats
  serial_groups: [bosh-lite-linux]
  plan:
  - aggregate:
    - get: cf-cli
      passed: [linux64-unit]
    - get: cli-ci
      trigger: false
    - get: gats
  - task: gats
    file: cf-cli/ci/gats.linux.yml
    config:
      params:
        BOSH_LITE_IP: {{bosh-lite-ip-linux}}

- name: windows64-cats
  serial_groups: [bosh-lite-windows]
  plan:
  - aggregate:
    - get: cf-cli
      passed: [windows64-unit]
    - get: cli-ci
      trigger: false
    - get: cf-release
      trigger: false
      passed: [provision-windows]
      params:
        submodules:
          - src/acceptance-tests
  - task: cats
    file: cf-cli/ci/cats.windows.yml
    config:
      params:
        BOSH_LITE_IP: {{bosh-lite-ip-windows}}

# - name: windows64-gats
#   serial_groups: [bosh-lite-windows]
#   plan:
#   - aggregate:
#     - get: cf-cli
#       passed: [windows64-unit]
#     - get: cli-ci
#       trigger: false
#     - get: gats
#   - task: gats
#     file: cf-cli/ci/gats.windows.yml
#     config:
#       params:
#         BOSH_LITE_IP: {{bosh-lite-ip-windows}}
#
- name: provision-linux
  serial: true
  plan:
  - aggregate:
    - get: cli-ci
      trigger: false
    - get: cf-release
      trigger: false
      params:
        submodules: none
    - get: bosh-lite
      trigger: false
  - task: provision
    privileged: true
    file: cli-ci/concourse/lite/provision-cf-lite.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
        LITE_NAME: linux
  - conditions: [success, failure]
    put: cli-ci
    params:
      repository: build/cli-ci
      rebase: true

- name: provision-windows
  serial: true
  plan:
  - aggregate:
    - get: cli-ci
      trigger: false
    - get: cf-release
      trigger: false
      params:
        submodules: none
    - get: bosh-lite
      trigger: false
  - task: provision
    privileged: true
    file: cli-ci/concourse/lite/provision-cf-lite.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{lite-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{lite-secret-access-key}}
        LITE_NAME: windows
  - conditions: [success, failure]
    put: cli-ci
    params:
      repository: build/cli-ci
      rebase: true

- name: deploy-concourse
  serial: true
  plan:
  - aggregate:
    - get: concourse
      trigger: false
    - get: cli-ci
      trigger: false
    - get: aws-stemcell
      trigger: false
  - put: concourse-deployment
    params:
      manifest: cli-ci/ci/aws-vpc.yml
      releases:
      - concourse/concourse-*.tgz
      - concourse/garden-linux-*.tgz
      stemcells:
      - aws-stemcell/*.tgz
