---
resources:
- name: cf-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: concourse

- name: cli-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-ci.git
    branch: concourse
    private_key: {{ci-repo-private-key}}

- name: cf-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-lite.git
    branch: master

- name: cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: master

- name: bosh-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-lite.git
    branch: master

jobs:
- name: linux64-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.linux.yml

- name: darwin64-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.darwin.yml

- name: win64-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.windows.yml

- name: linux64-acceptance
  plan:
  - aggregate:
    - get: cf-cli
      passed: [linux64-unit]
      trigger: false
    - get: cli-ci
      trigger: false
    - get: cf-release
      passed: [provision]
      params:
        submodules:
          - src/acceptance-tests
  - task: acceptance
    file: cf-cli/ci/cats.linux.yml
    config:
      params:
        BOSH_LITE_IP: {{bosh-lite-ip}}

- name: provision
  serial: true
  plan:
  - aggregate:
    - get: cli-ci
      trigger: false
    - get: cf-release
      trigger: false
      params:
        submodules: none
    - get: bosh-lite
      trigger: false
  - task: build
    privileged: true
    file: cli-ci/concourse/lite/provision-cf-lite.yml
  - conditions: [success, failure]
    put: cli-ci
    params:
      repository: build/cli-ci
      rebase: true
