---
groups:
- name: cli
  jobs:
  - linux64-unit
  - linux32-unit
  - darwin64-unit
  - win64-unit
  - linux64-gats
  - linux64-cats
- name: bosh-lite
  jobs: [provision]
- name: concourse
  jobs: [deploy-concourse]

resources:
- name: cf-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: concourse

- name: cli-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-ci.git
    branch: concourse
    private_key: {{ci-repo-private-key}}

- name: cf-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-lite.git
    branch: master

- name: cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: master

- name: bosh-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-lite.git
    branch: master

- name: gats
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/GATS
    branch: master

- name: concourse-deployment
  type: bosh-deployment
  source:
    target: {{concourse-bosh-target}}
    username: {{concourse-bosh-username}}
    password: {{concourse-bosh-password}}
    deployment: concourse
    ignore_ssl: true

- name: concourse
  type: github-release
  source:
    user: concourse
    repository: concourse

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

jobs:
- name: linux64-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.linux.yml

- name: linux32-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.linux32.yml

- name: darwin64-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.darwin.yml

- name: win64-unit
  plan:
  - get: cf-cli
  - task: unit-tests
    file: cf-cli/ci/unit.windows.yml

- name: linux64-cats
  serial_groups: [bosh-lite]
  plan:
  - aggregate:
    - get: cf-cli
      passed: [linux64-unit]
    - get: cli-ci
      trigger: false
    - get: cf-release
      trigger: false
      passed: [provision]
      params:
        submodules:
          - src/acceptance-tests
  - task: cats
    file: cf-cli/ci/cats.linux.yml
    config:
      params:
        BOSH_LITE_IP: {{bosh-lite-ip}}

- name: linux64-gats
  serial_groups: [bosh-lite]
  plan:
  - aggregate:
    - get: cf-cli
      passed: [linux64-unit]
    - get: cli-ci
      trigger: false
    - get: gats
  - task: gats
    file: cf-cli/ci/gats.linux.yml
    config:
      params:
        BOSH_LITE_IP: {{bosh-lite-ip}}

- name: provision
  serial: true
  plan:
  - aggregate:
    - get: cli-ci
      trigger: false
    - get: cf-release
      trigger: false
      params:
        submodules: none
    - get: bosh-lite
      trigger: false
  - task: build
    privileged: true
    file: cli-ci/concourse/lite/provision-cf-lite.yml
  - conditions: [success, failure]
    put: cli-ci
    params:
      repository: build/cli-ci
      rebase: true

- name: deploy-concourse
  serial: true
  plan:
  - aggregate:
    - get: concourse
      trigger: false
    - get: cli-ci
      trigger: false
    - get: aws-stemcell
      trigger: false
  - put: concourse-deployment
    params:
      manifest: cli-ci/ci/aws-vpc.yml
      releases:
      - concourse/concourse-*.tgz
      - concourse/garden-linux-*.tgz
      stemcells:
      - aws-stemcell/*.tgz
